/**
 * Created By:			  James Rogers
 * Created On:			  03/29/2020
 * Last Modified By:	James Rogers
 * Last Modified On:	03/29/2020
 * Purpose:			      Prints a fun banner for the project
 */

public class Banner {

  // Empty constructor
  // Banner is seperated into its own class for ease of removal if necessary
  public Banner() {}

  // Prints a project banner (generated by http://patorjk.com/software/taag/).
  public static void show() {

    System.out.println("                                             ");
    System.out.println("   ____             _   _             _      ");
    System.out.println("  / ___|  ___  _ __| |_(_)_ __   __ _| |     ");
    System.out.println("  \\___ \\ / _ \\| '__| __| | '_ \\ / _` | | ");
    System.out.println("   ___) | (_) | |  | |_| | | | | (_| |_|     ");
    System.out.println("  |____/ \\___/|_|   \\__|_|_| |_|\\__, (_)  ");
    System.out.println("                                |___/        ");
    System.out.println("                                             ");

  }

}
