/**
 * Created By:			  James Rogers
 * Created On:			  02/24/2020
 * Last Modified By:	James Rogers
 * Last Modified On:	02/24/2020
 * Purpose:			      Prints a fun banner for the project
 */

public class Banner {

  // Empty constructor
  // Banner is seperated into its own class for ease of removal if necessary
  public Banner() {}

  // Prints a project banner (generated by http://patorjk.com/software/taag/).
  public static void show() {
    System.out.println("                                                                                  ");
    System.out.println("       _____ _______ __  __                       _   _____      _                ");
    System.out.println("      |  __ \\__   __|  \\/  |                     | | |  __ \\    (_)            ");
    System.out.println("      | |  | | | |  | \\  / |___    __ _ _ __   __| | | |__) |_ _ _ _ __ ___      ");
    System.out.println("      | |  | | | |  | |\\/| / __|  / _` | '_ \\ / _` | |  ___/ _` | | '__/ __|    ");
    System.out.println("      | |__| | | |  | |  | \\__ \\ | (_| | | | | (_| | | |  | (_| | | |  \\__ \\  ");
    System.out.println("      |_____/  |_|  |_|  |_|___/  \\__,_|_| |_|\\__,_| |_|   \\__,_|_|_|  |___/   ");
    System.out.println("                                                                                  ");
  }

}
